(in-package :sl-user)

(format t "Loading tests takes a few seconds, please wait...~%")

(let* ((timing (list 0 0))
       (%:*load-timing* timing))
  (load "test/deftest.lisp")

  (load "test/apply.lisp")
  (load "test/funcall.lisp")
  (load "test/prog1.lisp")
  (load "test/prog2.lisp")
  (load "test/progv.lisp")
  (load "test/prog.lisp")
  (load "test/or.lisp")
  (load "test/and.lisp")
  (load "test/let.lisp")
  (load "test/letstar.lisp")
  (load "test/defun.lisp")
  (load "test/flet.lisp")
  (load "test/labels.lisp")
  (load "test/places.lisp")

  (load "test/values.lisp")
  (load "test/values-list.lisp")
  (load "test/multiple-value-bind.lisp")
  (load "test/multiple-value-call.lisp")
  (load "test/multiple-value-list.lisp")
  (load "test/multiple-value-prog1.lisp")
  (load "test/multiple-value-setq.lisp")

  (load "test/if.lisp")
  (load "test/cond.lisp")
  (load "test/case.lisp")
  (load "test/destructuring-bind.lisp")
  (load "test/macrolet.lisp")

  (load "test/block.lisp")
  (load "test/catch.lisp")
  (load "test/unwind-protect.lisp")
  (load "test/tagbody.lisp")

  (load "test/do.lisp")
  (load "test/dolist.lisp")
  (load "test/dostar.lisp")
  (load "test/dotimes.lisp")

  (load "test/loop1.lisp")
  (load "test/loop2.lisp")
  (load "test/loop3.lisp")
  (load "test/loop4.lisp")

  (load "test/handler-bind.lisp")
  (load "test/handler-case.lisp")
  (load "test/ignore-errors.lisp")
  (load "test/error.lisp")

  (load "test/cons/append.lisp")
  (load "test/cons/member.lisp")
  (load "test/cons/adjoin.lisp")
  (load "test/cons/getf.lisp")
  (load "test/cons/pop.lisp")
  (load "test/cons/push.lisp")
  (load "test/cons/pushnew.lisp")
  (load "test/cons/acons.lisp")
  (load "test/cons/pairlis.lisp")
  (load "test/cons/butlast.lisp")
  (load "test/cons/subst.lisp")
  (load "test/cons/sublis.lisp")
  (load "test/cons/assoc.lisp")
  (load "test/cons/assoc-if.lisp")
  (load "test/cons/assoc-if-not.lisp")
  (load "test/cons/rassoc.lisp")
  (load "test/cons/rassoc-if.lisp")
  (load "test/cons/rassoc-if-not.lisp")
  (load "test/cons/intersection.lisp")
  (load "test/cons/union.lisp")
  (load "test/cons/set-difference.lisp")

  (load "test/seq/count.lisp")
  (load "test/seq/count-if.lisp")
  (load "test/seq/count-if-not.lisp")
  (load "test/seq/find.lisp")
  (load "test/seq/find-if.lisp")
  (load "test/seq/find-if-not.lisp")
  (load "test/seq/position.lisp")
  (load "test/seq/position-if.lisp")
  (load "test/seq/position-if-not.lisp")
  (load "test/seq/substitute.lisp")
  (load "test/seq/substitute-if.lisp")
  (load "test/seq/substitute-if-not.lisp")
  (load "test/seq/nsubstitute.lisp")
  (load "test/seq/nsubstitute-if.lisp")
  (load "test/seq/nsubstitute-if-not.lisp")
  (load "test/seq/subseq.lisp")
  (load "test/seq/remove.lisp")

  (format t "Network time: ~,2Fms~%~
             Compile time: ~,2Fms~%"
          (car timing)
          (cadr timing)))
