(in-package :sl-user)

(let* ((timing (list 0 0))
       (%:*load-timing* timing))
  (load "test/deftest.lisp")

  (load "test/apply.lisp")
  (load "test/funcall.lisp")
  (load "test/prog1.lisp")
  (load "test/prog2.lisp")
  (load "test/progv.lisp")
  (load "test/prog.lisp")
  (load "test/or.lisp")
  (load "test/and.lisp")
  (load "test/let.lisp")
  (load "test/letstar.lisp")
  (load "test/defun.lisp")
  (load "test/flet.lisp")
  (load "test/labels.lisp")

  (load "test/values.lisp")
  (load "test/values-list.lisp")
  (load "test/multiple-value-bind.lisp")
  (load "test/multiple-value-call.lisp")
  (load "test/multiple-value-list.lisp")
  (load "test/multiple-value-prog1.lisp")
  (load "test/multiple-value-setq.lisp")

  (load "test/if.lisp")
  (load "test/cond.lisp")
  (load "test/case.lisp")
  (load "test/destructuring-bind.lisp")
  (load "test/macrolet.lisp")

  (load "test/block.lisp")
  (load "test/catch.lisp")
  (load "test/unwind-protect.lisp")
  (load "test/tagbody.lisp")

  (load "test/do.lisp")
  (load "test/dolist.lisp")
  (load "test/dostar.lisp")
  (load "test/dotimes.lisp")

  (load "test/loop1.lisp")
  (load "test/loop2.lisp")
  (load "test/loop3.lisp")
  (load "test/loop4.lisp")

  (load "test/handler-bind.lisp")
  (load "test/handler-case.lisp")
  (load "test/ignore-errors.lisp")
  (load "test/error.lisp")

  (format t "Network time: ~Ams~%Compile time: ~Ams~%"
          (car timing)
          (cadr timing)))
